### ISSUE TITLE
RH SO Showing different site type location in the same cluster

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#10]
**Describe the bug**
Showing different site type location dropdown options even though the projects are from the same 1 cluster.

**Context**
I found this bug when I explore the ReportHub in Somalia

**To Reproduce**
1. Login to your Somalia account
2. Go to the following link :
https://reporthub.org/desk/#/cluster/projects/details/60af3b0c9071f21a5c063767
https://reporthub.org/desk/#/cluster/projects/details/60dad7fc66f84aa238a0cf5b
https://reporthub.org/desk/#/cluster/projects/details/6022c515b6674f644edf1dfb
3. Scroll down to "Target Location" section
4. Open the "Type"
5. Compare the list between each link
6. See the error where the options list showing is different even though all of the projects are from the Health cluster

**Expected behavior**
The platform should show the same options list if the projects are from the same 1 cluster

**Screenshots**

**Additional context**
If this bug isn't fixed, the reporting partners in Somalia might choose the wrong "Site Type" Location resulting in the incorrect data report
After fixing this bug, the focal point should inform the reporting partners to check their site type location.
We'll also probably need to clean up the database after fixing this issue.

**Comment by fakhrihawari** [comment]
Already fix this 
Link PR
https://github.com/iMMAP/ngm-reportHub/pull/101
