### ISSUE TITLE
Tokenized API

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#11]
Moving https://github.com/rafinkanisa/ngm-reportDesk/issues/151. Leftover the previous project lead plan

**Is your feature request related to a problem? Please describe.**
The API in ReportHub can be accessed publicly as long as the user has the link. It has been planned by the previous lead that ReportHub should move to the tokenized direction

**Describe the solution you'd like**
When a user opens the API link, the platform should ask the token to authenticate the data the user retrieving are based on the account rights. For example, if the user has only cluster rights, this API should show the data on cluster levels not country level

What to do :

- [x] Tokenized the API
- [x] Show the token on the profile page
- [x] The token could be easily copied using a single button
- [x] Ask the capacity building team to build a usage documentation
- [x] Store the documentation and share only to necessary person
- [x] Launch the tokenized API in the live server

**Describe alternatives you've considered**

**Additional context**
After finishing the API token we'll need the cooperation from the capacity building team to build a step by step document describing on how to use the API using an example case (possibly with the PowerBI)
We'll need to assess how the changes will affect the dashboard which has been previously made

**Comment by rafinkanisa** [comment]
Hi! I've just tried the tokenized API in the DEV but below message is appearing. I tried using an acoount with country & cluster admin rights. Kindly check.

1. Open incognito mode
2. https://dev.reporthub.immap.org/api/cluster/indicator?adminRpcode=emro&admin0pcode=af&admin1pcode=all&admin2pcode=all&cluster_id=health&organization_tag=all&start_date=2021-11-01&end_date=2021-11-30&indicator=beneficiaries&beneficiaries[]=all&ocha=true&csv=true&reportname=example_health_api_nov_2021&api_key=<your_token>

<img width="1680" alt="Screen Shot 2022-01-19 at 09 11 24" src="https://user-images.githubusercontent.com/28089698/150051184-069fb08f-f829-47f7-9dc6-b56b343a6dcf.png">

**Comment by fakhrihawari** [comment]
Still on DEV,
Link PR:
https://github.com/iMMAP/ngm-reportEngine/pull/49

**Comment by sud0su** [comment]
the API tokenization validation on all indicators has been developed and needs review and testing on the dev server.
Link PR:
[iMMAP/ngm-reportEngine#50](https://github.com/iMMAP/ngm-reportEngine/pull/50)

**Comment by rafinkanisa** [comment]
Just received the final guide of the API from the capacity building officer. If all is good, we can launch this in the next 2 week

**Comment by fakhrihawari** [comment]
Updated On DEV

**Comment by fakhrihawari** [comment]
Already updated on DEV and PROD.
Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/118
https://github.com/iMMAP/ngm-reportEngine/pull/52
