### ISSUE TITLE
RH ET Duplicate Stock Report

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#12]
**Describe the bug**
The data remnants which is the result of previous bugs that has been fixed a couple of months ago. The data is left uncleaned at that time. Read https://github.com/rafinkanisa/ngm-reportDesk/issues/130 issue

**Context**
I couldn't remember who is reporting this bug but this is reported by a reporting partner in Afghanistan to Rafinka. Rafinka checks this bug and learned that this is also happening in the other country as well. So, there are duplicated stock report as well in Ethiopia

**To Reproduce**
1. Login using Ethiopia account
2. Go to '...'
3. See error where there are duplicated stock reports submitted

**Expected behavior**
All of the duplicated Stock Report in the same month should be removed

**Screenshots**

**Additional context**
If the stock report is left uncleaned, the monitoring partners who are using this data will be given out false information

**Comment by fakhrihawari** [comment]
Already run the fixed script and run it on PROD Server
