### ISSUE TITLE
RH AF WASH Activity for HRP 2022

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#13]
Moving https://github.com/rafinkanisa/ngm-reportDesk/issues/187

**Is your feature request related to a problem? Please describe.**
As the 2022 HRP has just been published, we'll have to update the configuration list in WASH cluster accordingly so this can be used for reporting the January report.

**Describe the solution you'd like**
Update the following list accordingly based on their inputs from the returned configuration files

- [x] Activity List
- [x] Beneficiary List (optional)
- [ ] Donor List (optional)

**Acceptance Criteria**

- [x] The updated list is showing in Monthly Progress starting at Jan 2022
- [x] The updated list is showing in Activity Plan that has the start project date at Jan 2022 and/or ending at Dec 2022

**What to do**

- [x] Send the configuration list to the cluster coordinator
- [x] Received the returned configuration list file from the clusters
- [x] Analyze and confirm the missing part
- [x] Compile the CSV file
- [x] Update the list accordingly to the system

**Describe alternatives you've considered**
No alternatives

**Additional context**
You can find the related document here
https://www.humanitarianresponse.info/en/operations/afghanistan/document/afghanistan-humanitarian-response-plan-2022
Expected date for this update to be used in February

**Comment by rafinkanisa** [comment]
I have sent the cluster coordinator the configuration list at 23 Dec 2021

**Comment by rafinkanisa** [comment]
I've just received the configuration files from the WASH cluster on 20 Jan 2022. 
I've done analyzing their configuration files and asked them to fill in the missing information. I also have done a meeting with them to clarify their request. Basically, they're requesting to add some more tier dropdowns in several things.
Because we need to standardize using the ReportHub standard, I've just negotiated with them so it'll be look like below screenshots :
<img width="1113" alt="Screen Shot 2022-01-20 at 15 24 04" src="https://user-images.githubusercontent.com/28089698/150564320-21558c34-5c07-42d0-9a80-932a2fb9366e.png">

Kindly check if there're any missing things in the CSV file. I have added 640 rows in the activity list.
After that please update on DEV and ensure everything works well
Once you've sure that no bugs occurred, update it on PROD

What you should update :

- Activity List
- Beneficiary List

**Comment by fakhrihawari** [comment]
Updated on PROD:
1. Activity List
2. Beneficiary List

And ad-hoc request to make "WASH Supplies" automatic checked if project reporting activity :
1. Family Hygiene Kits Distributed
2. Family Water Kit Distribution

Script to update

// wash suplies update script
use ngmHealthCluster
db.project.find({ admin0pcode: "AF", "activity_type.activity_type_name": { $in: ["Water", "Hygiene"] }, $and: [{ project_end_date: { $gte: ISODate('2022-01-01') } }, { project_start_date: { $lt: ISODate('2022-02-01') } }]  }).forEach(function (p) {
	if (p.activity_type.length) {
		
        var _beneficiaries = db.beneficiaries.aggregate([{ $match: { project_id: p._id.valueOf(), $or: [{ activity_description_name: "Family Hygiene Kits Distributed" }, { activity_description_name: "Family Water Kit Distribution" }] }}]).toArray();
		if(_beneficiaries.length >0){
			print("PROJECT", p._id.valueOf())
		}
	}
});

// simpler version
db.project.find({ admin0pcode: "AF", "activity_type.activity_type_name": { $in: ["Water", "Hygiene"] }, $and: [{ project_end_date: { $gte: ISODate('2022-01-01') } }, { project_start_date: { $lt: ISODate('2022-02-01') } }] }).forEach(function(p){
	if (p.activity_type.length) {
		var obj = {
			cluster: "WASH",
			cluster_id: "wash",
			activity_type_id: "wash_supplies",
			activity_type_name: "WASH Supplies"
		}

        var _beneficiaries = db.beneficiaries.aggregate([{ $match: { project_id: p._id.valueOf(), $or: [{ activity_description_name: "Family Hygiene Kits Distributed" }, { activity_description_name: "Family Water Kit Distribution" }] } }]).toArray();
		if (_beneficiaries.length > 0) {
			db.targetlocation.find({ project_id: p._id.valueOf() }).forEach(function (tl) {
				tl.activity_type.push(obj);
				db.beneficiaries.save(tl);
			})
			db.targetbeneficiaries.find({ project_id: p._id.valueOf() }).forEach(function (tb) {
				tb.activity_type.push(obj);
				db.beneficiaries.save(tb);
			})
			db.report.find({ project_id: p._id.valueOf()}).forEach(function (r) {
				r.activity_type.push(obj);
				db.report.save(r);
			})
			db.beneficiaries.find({ project_id: p._id.valueOf() }).forEach(function (b) {
				b.activity_type.push(obj);
				db.beneficiaries.save(b);
			})
			p.activity_type.push(obj);
			db.project.save(p)
			print(p._id.valueOf())
		}
	}
})
