### ISSUE TITLE
RH AF ESNFI Activity for 2022

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#15]
Moving https://github.com/rafinkanisa/ngm-reportDesk/issues/189

**Is your feature request related to a problem? Please describe.**
As the 2022 HRP has just been published, we'll have to update the configuration list in ESNFI cluster accordingly so this can be used for reporting the January report.

**Describe the solution you'd like**
Update the following list accordingly based on their inputs from the returned configuration files

- [x] Activity List
- [x] Beneficiary List (optional)
- [ ] Donor List (optional)

**Acceptance Criteria**

- [x] The updated list is showing in Monthly Progress starting at Jan 2022
- [x] The updated list is showing in Activity Plan that has the start project date at Jan 2022 and/or ending at Dec 2022

**What to do**

- [x] Send the configuration list to the cluster coordinator
- [x] Received the returned configuration list file from the clusters
- [x] Analyze and confirm the missing part
- [x] Compile the CSV file
- [x] Update the list accordingly to the system

**Describe alternatives you've considered**
No alternatives

**Additional context**
You can find the related document here
https://www.humanitarianresponse.info/en/operations/afghanistan/document/afghanistan-humanitarian-response-plan-2022
Expected date for this update to be used in February

**Comment by rafinkanisa** [comment]
I have sent the cluster coordinator the configuration list at 23 Dec 2021

**Comment by rafinkanisa** [comment]
I've just received the configuration file on 20 Jan 2022 late at night. I've analyzed the list and checked with them the missing part. The only thing that still missing is only the indicator for 3 activities about capacity building. They told me they would be informing me about those indicators on Sunday.

Kindly check all of the lists in case I missed some things @fakhrihawari 
After that please update the following :

- Activity List
- Beneficiary Type

**Comment by fakhrihawari** [comment]
Okay, there are some activities that missing input on certain field and some that wrong input 
for example :
[{"grant_type_id" : "conditional_restricted","grant_type_name" : "Conditional, Restricted"}][{"grant_type_id" : "unconditional_unrestricted","grant_type_name" : "Unconditional, Unrestricted"}]
 it should be [{"grant_type_id" : "conditional_restricted","grant_type_name" : "Conditional, Restricted"},{"grant_type_id" : "unconditional_unrestricted","grant_type_name" : "Unconditional, Unrestricted"}]

already fixed in activieties.csv

**Comment by fakhrihawari** [comment]
The new lists were already updated last week on 27 Jan 2022

**Comment by rafinkanisa** [comment]
Received feedback from their side at 02 Feb 2022
They're requesting the following

- [x] Changing some of the wording of the Activity Type Name in 2022 that has a similar definition to be the same as 2021 (e.g. Permanent Shelter Support -> Permanent Shelter)
- [x] Make the 2021 winterization activity (Standard Winterization Packages (blankets/clothing/heating)) which still ongoing to be available until 31 March 2022
- [x] The new winterization activity (Standard Winterization Assistance) will be available starting from 01 April 2022 onwards
- [x] Remove “Sealing Off Kit” from the 2022 Activity List
- [x] Change “Shelter Repair/Reconstruction Toolkit” to “Shelter Repair/Reconstruction Kit”

Expected date to be fixed before 03 Feb 2022

**Comment by fakhrihawari** [comment]
Changing some of the wording of the Activity Type Name in 2022 that has a similar definition to be the same as 2021

<img width="559" alt="Screen Shot 2022-02-02 at 14 45 59" src="https://user-images.githubusercontent.com/12655589/152480020-ba26ca22-78b1-48d3-92e2-67f6c8a2930a.png">

Remove “Sealing Off Kit” from the 2022 Activity List
<img width="1263" alt="Screen Shot 2022-02-02 at 15 01 11" src="https://user-images.githubusercontent.com/12655589/152480106-353b85a3-a77f-4fdb-a05c-efbf85e2840b.png">

Change “Shelter Repair/Reconstruction Toolkit” to “Shelter Repair/Reconstruction Kit”
<img width="1149" alt="Screen Shot 2022-02-02 at 14 46 40" src="https://user-images.githubusercontent.com/12655589/152479848-3ff0e57a-2762-4bb6-8ed1-f9130b5f2cb6.png">
