### ISSUE TITLE
RH AF Protection Activity for HRP 2022

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#16]
Moving https://github.com/rafinkanisa/ngm-reportDesk/issues/190

**Is your feature request related to a problem? Please describe.**
As the 2022 HRP has just been published, we'll have to update the configuration list in Protection cluster accordingly so this can be used for reporting the January report.

**Describe the solution you'd like**
Update the following list accordingly based on their inputs from the returned configuration files

- [x] Activity List
- [ ] Beneficiary List (optional)
- [ ] Donor List (optional)

**Acceptance Criteria**

- [ ] The updated list is showing in Monthly Progress starting at Jan 2022
- [ ] The updated list is showing in Activity Plan that has the start project date at Jan 2022 and/or ending at Dec 2022

**What to do**

- [x] Send the configuration list to the cluster coordinator
- [x] Received the returned configuration list file from the clusters
- [x] Analyze and confirm the missing part
- [x] Compile the CSV file
- [x] Update the list accordingly to the system

**Describe alternatives you've considered**
No alternatives

**Additional context**
You can find the related document here
https://www.humanitarianresponse.info/en/operations/afghanistan/document/afghanistan-humanitarian-response-plan-2022
Expected date for this update to be used in February

**Comment by rafinkanisa** [comment]
I have sent the cluster coordinator the configuration list at 21 Dec 2021

**Comment by fakhrihawari** [comment]
The new lists were already updated last week on 27 Jan 2022

**Comment by rafinkanisa** [comment]
Adding notes
has confirmed to the cluster focal point to enable cash inputs for the following activities
<img width="1374" alt="Screen Shot 2022-02-08 at 15 39 06" src="https://user-images.githubusercontent.com/28089698/152949520-b91962c6-d399-40b7-83c1-89ce074e7055.png">


confirmed to also collect below data for following activities
<img width="1458" alt="Screen Shot 2022-02-08 at 15 38 55" src="https://user-images.githubusercontent.com/28089698/152949492-94cb22a6-8d29-480f-8458-c12f8bc42eaf.png">
