### ISSUE TITLE
RH AF FSAC Activity for HRP 2022

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#17]
Moving https://github.com/rafinkanisa/ngm-reportDesk/issues/191

**Is your feature request related to a problem? Please describe.**
As the 2022 HRP has just been published, we'll have to update the configuration list in FSAC cluster accordingly so this can be used for reporting the January report.

**Describe the solution you'd like**
Update the following list accordingly based on their inputs from the returned configuration files

- [ ] Activity List
- [x] Beneficiary List (optional)
- [ ] Donor List (optional)

**Acceptance Criteria**

- [ ] The updated list is showing in Monthly Progress starting at Jan 2022
- [ ] The updated list is showing in Activity Plan that has the start project date at Jan 2022 and/or ending at Dec 2022

**What to do**

- [x] Send the configuration list to the cluster coordinator
- [x] Received the returned configuration list file from the clusters
- [ ] Analyze and confirm the missing part
- [ ] Compile the CSV file
- [ ] Update the list accordingly to the system

**Describe alternatives you've considered**
No alternatives

**Additional context**
You can find the related document here
https://www.humanitarianresponse.info/en/operations/afghanistan/document/afghanistan-humanitarian-response-plan-2022
Expected date for this update to be used in February

**Comment by rafinkanisa** [comment]
I have sent the cluster coordinator the configuration list at 23 Dec 2021 and just received the returned files at 09 Jan 2022
I already analyze the config list and there are some missing part. Need to setup a meeting with them. The previous scheduled meeting is being canceled

**Comment by fakhrihawari** [comment]
Already updated on PROD on 27 Jan 2022

**Comment by rafinkanisa** [comment]
The activity list is the same as the previous year. Only configure the beneficiary list.
