### ISSUE TITLE
RH AF Health Activity for HRP 2022

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#18]
Moving https://github.com/rafinkanisa/ngm-reportDesk/issues/188

**Is your feature request related to a problem? Please describe.**
As the 2022 HRP has just been published, we'll have to update the configuration list in Health cluster accordingly so this can be used for reporting the January report.

**Describe the solution you'd like**
Update the following list accordingly based on their inputs from the returned configuration files

- [x] Activity List
- [x] Beneficiary List (optional)
- [x] Donor List (optional)

**Acceptance Criteria**

- [x] The updated list is showing in Monthly Progress starting at Jan 2022
- [x] The updated list is showing in Activity Plan that has the start project date at Jan 2022 and/or ending at Dec 2022

**What to do**

- [x] Send the configuration list to the cluster coordinator
- [x] Received the returned configuration list file from the clusters
- [x] Analyze and confirm the missing part
- [x] Compile the CSV file
- [x] Update the list accordingly to the system

**Describe alternatives you've considered**
No alternatives

**Additional context**
You can find the related document here
https://www.humanitarianresponse.info/en/operations/afghanistan/document/afghanistan-humanitarian-response-plan-2022
Expected date for this update to be used in February

**Comment by rafinkanisa** [comment]
I have sent the cluster coordinator the configuration list at 23 Dec 2021

**Comment by rafinkanisa** [comment]
I've just received the draft list on 21 Jan 2022. They'll still need time to finalize the list because I've analyzed and let them know there are some missing activities that can be found in the HRP document but doesn't reflect in the list they've compiled.

I've compiled all of the lists in the CSV, the activity list is still drafted so, I'll update once they send me the final list.

What you need to do :

- Update Activity List
- Update Beneficiary List
- Update Donor List

**Comment by fakhrihawari** [comment]
already updated activity and beneficiary list on DEV

**Comment by fakhrihawari** [comment]
already updated activity and beneficiary list on PROD

**Comment by rafinkanisa** [comment]
Adding notes :
The following unit is added accordingly
<img width="1174" alt="Screen Shot 2022-02-09 at 17 28 57" src="https://user-images.githubusercontent.com/28089698/153179949-1f4e6b37-d01f-48bc-802a-4c6fad90ffc0.png">

Number 23 & 24 is merged
