### ISSUE TITLE
RH SO Health Activity for HRP 2022

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#19]
**Is your feature request related to a problem? Please describe.**
As the 2022 HRP has just been published, we'll have to update the configuration list in Health cluster at Somalia accordingly so this can be used for reporting the January report.

**Describe the solution you'd like**
Update the following list accordingly based on their inputs from the returned configuration files

- [x] Activity List
- [ ] Beneficiary List (optional)
- [ ] Donor List (optional)

**Acceptance Criteria**

- [x] The updated list is showing in Monthly Progress starting at Jan 2022
- [x] The updated list is showing in Activity Plan that has the start project date at Jan 2022 and/or ending at Dec 2022

**What to do**

- [x] Send the configuration list to the Somalia focal point
- [x] Received the returned configuration list file from the focal point
- [x] Analyze and confirm the missing part
- [x] Compile the CSV file
- [x] Update the list accordingly to the system

**Describe alternatives you've considered**
No alternatives

**Additional context**
You can find the related document here
https://www.humanitarianresponse.info/en/operations/somalia/document/somalia-humanitarian-response-plan-humanitarian-programme-cycle-2022
Expected date for this update to be used in February

**Comment by rafinkanisa** [comment]
I have sent the focal point the configuration list at 10 Jan 2021

**Comment by rafinkanisa** [comment]
Hi I've just received the files and have analyzed it. Please update in the DEV @fakhrihawari

**Comment by fakhrihawari** [comment]
Already updated on DEV

**Comment by fakhrihawari** [comment]
Already updated on PROD
