### ISSUE TITLE
RH NG Clean Older Reporting Structure

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#22]
**Describe the bug**
In Nigeria there is a leftover of older reporting structure of one organization account per cluster, existing before 2019
in 2019 it has become one organization per country, and organizations updated only in Afghanistan

As a reference please see the issue here
https://github.com/pfitzpaddy/ngm-reportDesk/issues/127

**Context**
We realized this bug last year when a colleague from Ethiopia reported an issue of can not choose a warehouse created by the other colleague even though they're from the same organization. After further investigation, we know that this bug not only happening in Ethiopia but also in other countries as well. The only country that has already been cleaned up is Afghanistan only.

**To Reproduce**
1. Login using Nigeria account
2. Go to 
https://reporthub.org/desk/#/cluster/stocks/organization/5bfbf0607eced14c4daf4b15/2018
https://reporthub.org/desk/#/cluster/stocks/organization/5b606b823949dd7c3e30021a/2018
https://reporthub.org/desk/#/cluster/stocks/organization/5b39f6018e703fe74c213ba6/2018 
3. See Warehouse Locations and Stock Reports
4. See error where each links shows differently while the 3 of them are from the same organization

**Expected behavior**
Clean all of related collections in ReportHub Nigeria

**Screenshots**

**Additional context**
Kindly share the script here.

**Comment by rafinkanisa** [comment]
Hi @sud0su I would like you to take over this task from @fakhrihawari since he is very busy with updating RH.
After further investigation, there are so many collections need to be cleaned up
It's not possible to use the script to clean it up because there are still some inconsistency in many collections. You'll have to look at it one by one.

I only explain in the above one of the impact, but in reality, there are lots of other things got affected by this 

@fakhrihawari please explain :

- where you left
- what collections should be cleaned

**Comment by sud0su** [comment]
I have sent the code to clean up organizations in Nigeria to @fakhrihawari  for review, I made the script with the help of @dodiws , who has experience in cleaning up data previously.

https://github.com/rafinkanisa/ngm-reportDesk/issues/18#issuecomment-989611397

**Comment by fakhrihawari** [comment]
already  on PROD
