### ISSUE TITLE
RH AF WASH Select New Activity Type

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#31]
**Is your feature request related to a problem? Please describe.**
The WASH cluster is creating a new activity type in 2022. They're requesting us to automatically tick this new activity type for their partners because the reporting partners often didn't know that the activity is moving to the new activity type.

**Describe the solution you'd like**
Create a script to automatically tick the new activity type (WASH Supplies) if below activities have been reported in 2021 and the project is still continuing in 2022

- Family Water Kit Distribution
- Family Hygiene Kits Distributed

Do the same if there is a partner who has submitted the January 2022 report of those activities.
Please let me know the project id, email, focal point name of the report that has been submitting those activity in Jan 2022

**Describe alternatives you've considered**

**Additional context**

**Comment by fakhrihawari** [comment]
After I check There is no report  submitted in Jan 2022 using this activity 
Family Water Kit Distribution
Family Hygiene Kits Distributed

**Comment by fakhrihawari** [comment]
Script to update

// wash suplies update script
use ngmHealthCluster
db.project.find({ admin0pcode: "AF", "activity_type.activity_type_name": { $in: ["Water", "Hygiene"] }, $and: [{ project_end_date: { $gte: ISODate('2022-01-01') } }, { project_start_date: { $lt: ISODate('2022-02-01') } }] }).forEach(function (p) {
if (p.activity_type.length) {

    var _beneficiaries = db.beneficiaries.aggregate([{ $match: { project_id: p._id.valueOf(), $or: [{ activity_description_name: "Family Hygiene Kits Distributed" }, { activity_description_name: "Family Water Kit Distribution" }] }}]).toArray();
	if(_beneficiaries.length >0){
		print("PROJECT", p._id.valueOf())
	}
}
});

// simpler version
db.project.find({ admin0pcode: "AF", "activity_type.activity_type_name": { $in: ["Water", "Hygiene"] }, $and: [{ project_end_date: { $gte: ISODate('2022-01-01') } }, { project_start_date: { $lt: ISODate('2022-02-01') } }] }).forEach(function(p){
if (p.activity_type.length) {
var obj = {
cluster: "WASH",
cluster_id: "wash",
activity_type_id: "wash_supplies",
activity_type_name: "WASH Supplies"
}

    var _beneficiaries = db.beneficiaries.aggregate([{ $match: { project_id: p._id.valueOf(), $or: [{ activity_description_name: "Family Hygiene Kits Distributed" }, { activity_description_name: "Family Water Kit Distribution" }] } }]).toArray();
	if (_beneficiaries.length > 0) {
		db.targetlocation.find({ project_id: p._id.valueOf() }).forEach(function (tl) {
			tl.activity_type.push(obj);
			db.beneficiaries.save(tl);
		})
		db.targetbeneficiaries.find({ project_id: p._id.valueOf() }).forEach(function (tb) {
			tb.activity_type.push(obj);
			db.beneficiaries.save(tb);
		})
		db.report.find({ project_id: p._id.valueOf()}).forEach(function (r) {
			r.activity_type.push(obj);
			db.report.save(r);
		})
		db.beneficiaries.find({ project_id: p._id.valueOf() }).forEach(function (b) {
			b.activity_type.push(obj);
			db.beneficiaries.save(b);
		})
		p.activity_type.push(obj);
		db.project.save(p)
		print(p._id.valueOf())
	}
}

**Comment by fakhrihawari** [comment]
Already updated the DB
