### ISSUE TITLE
RH ET Clean Incorrect Activity Status

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#33]
**Describe the bug**
Related issue : https://github.com/iMMAP/ngm-reportDesk/issues/32

**Context**
This is an issue raised by the ReportHub focal person in Somalia and reported in a call meeting with me on Wed, 03 Feb 2022 at 18.30 (GMT +7).

**To Reproduce**
1. Login using Ethiopia account
2. Go to https://reporthub.org/desk/#/cluster/admin/afro/et/all/all/all/activity/2021-12-01/2021-12-31/all/all/all/all
3. Click on 'Download Beneficiary Data as CSV'
4. Open the downloaded file
5. Look for the column "activity_status"
6. See error where the submitted report that has specified "activity_end_date" and the date has already passed, the value of "activity_status" is ongoing

**Expected behavior**
All of the submitted reports in Ethiopia shall be cleaned. If the activity_end_date has been specified and the date has already passed change the activity_status to complete. So, please investigate other status as well and kindly clean the database accordingly.

**Screenshots**
<img width="448" alt="Screen Shot 2022-02-04 at 11 59 35" src="https://user-images.githubusercontent.com/28089698/152474621-91cef907-825a-4e4b-8b8f-8f08421de3a6.png">

**Additional context**

**Comment by fakhrihawari** [comment]
Script to solve this problem:
// set ongoing to complete
db.beneficiaries.find({admin0pcode:"ET",activity_status:"ongoing",  $and: [ { activity_end_date : {$exists:true} } , {activity_end_date : {$ne:""}}]}).count()
db.beneficiaries.update({admin0pcode:"ET",activity_status:"ongoing",  $and: [ { activity_end_date : {$exists:true} } , {activity_end_date : {$ne:""}}]},{$set:{activity_status:"complete"}},{multi:true})


// planned to complete
db.beneficiaries.find({admin0pcode:"ET",activity_status:"planned",  $and: [ { activity_start_date : {$exists:true} } , {activity_start_date : {$ne:""}},{activity_end_date : {$exists:true}},{activity_end_date : {$ne:""}}]}).count();
db.beneficiaries.update({ admin0pcode: "ET", activity_status: "planned", $and: [{ activity_start_date: { $exists: true } }, { activity_start_date: { $ne: "" } }, { activity_end_date: { $exists: true } }, { activity_end_date: { $ne: "" } }] },{$set:{activity_status:"complete"}},{multi:true})


//  ongoing to planned
db.beneficiaries.find({ admin0pcode: "ET", activity_status: "ongoing", $and: [{ activity_start_date: { $exists: true } }, { activity_start_date: { $eq: "" } }, { activity_end_date: { $exists: true } }, { activity_end_date: { $eq: "" } }] }).count();
db.beneficiaries.update({ admin0pcode: "ET", activity_status: "ongoing", $and: [{ activity_start_date: { $exists: true } }, { activity_start_date: { $eq: "" } }, { activity_end_date: { $exists: true } }, { activity_end_date: { $eq: "" } }] }, { $set: { activity_status: "planned"}},{multi:true});
