### ISSUE TITLE
RH ET Update Location List

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#34]
**Is your feature request related to a problem? Please describe.**
I'm communicating with the Ethiopia focal person and he told me that they would like to update the list of locations in ReportHub. Therefore, we'll have to update the location list in Ethiopia.

**Describe the solution you'd like**
Update the location list of ReportHub in Ethiopia

**Acceptance Criteria**

- [x] The updated list is showing in the Activity Plan at Target Location section of ReportHub in Ethiopia
- [x] There is no bugs occurring in other countries (AF, NG, SO) after updating the location list (check the Target Location in each countries)

**What to do**

- [x] Send the current location list to the focal person in Ethiopiia
- [x] Received the returned modified list file from the focal person
- [x] Analyze and confirm the missing part
- [x] Compile the CSV file
- [x] Update the list accordingly to the system

**Describe alternatives you've considered**
No alternatives

**Additional context**
Expected date for this update to be used in February
Please be careful when updating.

**Comment by fakhrihawari** [comment]
Extracted ET location lists from Database

**Comment by rafinkanisa** [comment]
I've received the shapefile of the updated location kindly proceed

**Comment by fakhrihawari** [comment]
updated on DEV

**Comment by rafinkanisa** [comment]
Hi! I've checked but I couldn't see the site location list

<img width="1131" alt="Screen Shot 2022-02-16 at 14 28 35" src="https://user-images.githubusercontent.com/28089698/154224936-5aa49bcd-9def-47a9-b6ad-26a8f574c396.png">

I think it's because the site list location hasn't been updated with the new corresponding region, zone and woreda code list?

**Comment by fakhrihawari** [comment]
I already updated

**Comment by rafinkanisa** [comment]
ok you can go to PROD

**Comment by fakhrihawari** [comment]
Updated on PROD and with little update on UI
https://github.com/iMMAP/ngm-reportHub/pull/117
