### ISSUE TITLE
RH AF WASH activate total pwd

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#35]
**Is your feature request related to a problem? Please describe.**
The WASH cluster focal point is reaching out and requesting to activate the total pwd instead of using the disaggregated person with disabilities which was used in last year

**Describe the solution you'd like**
Change the configuration of the activity to use total pwd

**Describe alternatives you've considered**
No alternatives

**Additional context**

**Comment by fakhrihawari** [comment]
already did the task, by updating wash activities
