### ISSUE TITLE
RH AF WASH Clean Database

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#36]
**Describe the bug**
Related with https://github.com/iMMAP/ngm-reportDesk/issues/35
As there are already some partners have submitted their report, we'll have to clean their data accordingly

**Context**
This is a task which I predict should be done when we modify the configuration

**To Reproduce**
1. Login to your Afghanistan account
2. Go to 'https://reporthub.org/desk/#/cluster/projects/report/614abf3766fd1df622fb22b6/61cfb5a2bfd464581ece8cbe'
3. Scroll down to one of the activity report
4. See error where field "Category" is still there

**Expected behavior**
the value of column beneficiary_category_name shall be blank
Clean only the submitted report data where it is using the 2022 activity. Exclude the report that submit using 2021 activity

**Screenshots**
<img width="1133" alt="Screen Shot 2022-02-03 at 16 19 47" src="https://user-images.githubusercontent.com/28089698/153177615-9c148658-9e5c-4c20-8fe5-05e7613590e4.png">

**Additional context**

**Comment by fakhrihawari** [comment]
Script to clean wash:

- db.beneficiaries.find({ admin0pcode: "AF", cluster_id: "wash", activity_type_id: { $ne: "cash_voucher" }, beneficiary_category_id: { $exists: true }, total_pwd: { $exists: true }, activity_detail_id: { $nin: ["regular", "response_covid19", "response_drought", "response_cholera"] }, createdAt: { $gte: ISODate('2022-02-01') }, report_year: 2022 }).count()

- db.beneficiaries.find({ admin0pcode: "AF", cluster_id: "wash", activity_type_id: { $ne: "cash_voucher" }, beneficiary_category_id: { $exists: true }, total_pwd: { $gt:0 }, activity_detail_id: { $nin: ["regular", "response_covid19", "response_drought", "response_cholera"] }, createdAt: { $gte: ISODate('2022-02-01') }, report_year: 2022 }).count()

- db.beneficiaries.update({ admin0pcode: "AF", cluster_id: "wash", activity_type_id: { $ne: "cash_voucher" }, beneficiary_category_id: { $exists: true }, total_pwd: { $exists: true }, activity_detail_id: { $nin: ["regular", "response_covid19", "response_drought", "response_cholera"] }, createdAt: { $gte: ISODate('2022-02-01') }, report_year: 2022 }, { $set: { beneficiary_category_id: "", beneficiary_category_name: "" } }, { multi: true })
