### ISSUE TITLE
RH AF Biweekly Copy Last Report not working

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#37]
**Describe the bug**
Copy last report button for biweekly reporting is not working

**Context**
This is a request from ESNFI cluster IM who found this bug and reported in a call meeting with me.

**To Reproduce**
1. Login to your afghanistan account
2. Go to https://reporthub.org/desk/#/cluster/projects/report/61bac0bcd56ebef03b784d69/61cfb5a2bfd464581ece8cdd/AF2401
3. Click on 'Copy Last Report'
4. See error where the last report can't be copied and said no data found

**Expected behavior**
The previous report shall be copied the same as copy last month report for monthly progress. If some activities are ending, it should also show the warning text

**Screenshots**

**Additional context**

**Comment by fakhrihawari** [comment]
There some mistake when define a params, already fixed:
Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/114
