### ISSUE TITLE
RH AF Adding HRP Beneficiaries 2022

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#4]
**Is your feature request related to a problem? Please describe.**
As the 2022 HRP has just been published, we'll have to update the list accordingly so this can be used for reporting the January report.

**Describe the solution you'd like**
Add the following HRP beneficiary list in Afghanistan to the platform. Below are the population group list for 2022 that I've communicated and agree with the OCHA.
- New IDPs in 2022
- New cross-border returnees in 2022 (at border or EC)
- New cross-border returnees in 2022 (at province of return)
- Natural disaster-affected 2022 (sudden-onset, non-displaced)
- Refugees and Asylum Seekers
- Vulnerable people with humanitarian needs

**Acceptance Criteria**

- [x] The updated HRP Beneficiary List is showing in the Project Plan at Target Population where the project starts in Jan 2022
- [x] The updated HRP Beneficiary List is showing in the Monthly/Biweekly Report starts from Jan 2022 report

**Describe alternatives you've considered**
No alternatives

**Additional context**
You can find the related document here 
https://www.humanitarianresponse.info/en/operations/afghanistan/document/afghanistan-humanitarian-response-plan-2022
Expected date for this update to be used in February

**Comment by fakhrihawari** [comment]
Updated on DEV

**Comment by rafinkanisa** [comment]
Hi well done! You can go on the PROD.
I'll come back here if some changes are needed.
I'm just putting notes here if the start date of a Project Plan is in 2021 and it ends in 2022, the platform will show the users both of the HRP beneficiary lists for 2021 & 2022 in the Activity Plan.

There is also an additional notes so partners wouldn't be confuse which Refugees should they choose in the Activity Plan.

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/106
