### ISSUE TITLE
Email notification when project is deleted

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#40]
**Is your feature request related to a problem? Please describe.**
In Afghanistan, the reporting partners are not allowed to delete their projects by themselves. They will have to request to delete the project and later the admin will delete that. Once it's being deleted by the admin, the reporting partner doesn't know that the project has been successfully deleted. As discussed with Naqi, it would be better to notify also the focal point of the project that the project has been deleted by email.

**Describe the solution you'd like**
Send an email notification to the focal point of the project when the admin has deleted the project.
Below is the narrative of the email :
Hi focal_point_name,

The following project has been successfully deleted by admin_name with details below.
Country : XX
Project Title : XX

**Acceptance Criteria**

- [x] Email notification is sent to the focal point once the admin click delete button
- [x] In the email, specify the following information : Country, Project Title, the admin name deleting the project

**Describe alternatives you've considered**
Manually inform the reporting partners that their project has been successfully deleted.

**Additional context**

**Comment by fakhrihawari** [comment]
Mock Up:
<img width="672" alt="Screen Shot 2022-03-22 at 10 22 42" src="https://user-images.githubusercontent.com/12655589/159401624-20787a39-fc70-4643-96cd-f2c9a064d2ca.png">

**Comment by rafinkanisa** [comment]
Remove the bullet point for

Admin: admin_name (admin_username)

**Comment by fakhrihawari** [comment]
<img width="799" alt="Screen Shot 2022-03-29 at 12 45 25" src="https://user-images.githubusercontent.com/12655589/160541771-2ceecadb-ec54-4e5c-8ad5-1f52a29b0b91.png">

**Comment by rafinkanisa** [comment]
Is this applicable outside AF? If not yet, kindly make it applicable for all other countries too.
Thanks

**Comment by fakhrihawari** [comment]
Okay, I will update it

**Comment by fakhrihawari** [comment]
Updated on DEV

**Comment by rafinkanisa** [comment]
Done check
can go to PROD

**Comment by fakhrihawari** [comment]
Updated on PROD
Link PR:
https://github.com/iMMAP/ngm-reportEngine/pull/57
https://github.com/iMMAP/ngm-reportHub/pull/132
