### ISSUE TITLE
The automatic selected date is not full month for January in My Admin page

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#41]
**Describe the bug**
The date selected automatically by the system is not selecting the whole days of the month of January. It only selects 1 Jan - 28 Jan

**Context**
I found this bug when Naqi is doing the training

**To Reproduce**
1. Login to your account
2. Click on 'My Home' > My Admin
3. Look for the date filter
4. See error where it doesn't automatically select the whole day of month January (1-31 January)

**Expected behavior**
The platform should automatically select the whole day of the month. In this case, 1 - 31 January should be automatically selected. 

**Screenshots**
<img width="1264" alt="Screen Shot 2022-02-08 at 12 55 19" src="https://user-images.githubusercontent.com/28089698/153169887-e998201a-a612-48c7-b159-6d25a91f68b0.png">

**Additional context**
I think it's probably because February has only 28 days?

**Comment by fakhrihawari** [comment]
already fixed
Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/115
