### ISSUE TITLE
RH NG WASH Add New Activity

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#43]
**Is your feature request related to a problem? Please describe.**
The WASH cluster focal point in Nigeria is reaching out and request to add a new activity

**Describe the solution you'd like**
Add the activity with the following details :
Activity -> Hygiene 
Description -> MHM Hygiene Promotion
Details -> MHM Hygiene Promotion
Beneficiary -> Women
Formula : 1 quantity > 1 HH and 2 women
Quantity (House Visits)

**Describe alternatives you've considered**

**Additional context**
Similar to this
<img width="1114" alt="Screen Shot 2022-02-10 at 18 23 32" src="https://user-images.githubusercontent.com/28089698/153403379-208b1e05-99d2-4426-9777-4077b6014ce2.png">

**Comment by fakhrihawari** [comment]
Mock up

<img width="1241" alt="Screen Shot 2022-02-14 at 10 43 44" src="https://user-images.githubusercontent.com/12655589/153797341-391bc6ba-eabc-4d93-9762-0ea987c6c202.png">

**Comment by rafinkanisa** [comment]
Looks good to me. I'll ask once more to the WASH cluster focal point in Nigeria to confirm.

**Comment by fakhrihawari** [comment]
Updated on DEV

**Comment by rafinkanisa** [comment]
Just got approval. Kindly put it in PROD

**Comment by fakhrihawari** [comment]
Updated on PROD
Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/116
