### ISSUE TITLE
RH AF Organization doesn't match with the defined organization in the platform

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#44]
**Describe the bug**
Similar to https://github.com/iMMAP/ngm-reportDesk/issues/39

**Context**
I found this when I'm trying to add organization and check on the database

**To Reproduce**
1. Open the database
2. Compare organization_tag, organization, organization_name, organization type in user collection with organization collection and organizations collection
3. You can see there are some inconsistencies in the data

**Expected behavior**
Any of the organization details in other related collections (e.g. user) should follow with collections "organization". This applies to all reporting collection as well. The organization collection shall refer the details to organizations collection. 

**Screenshots**

**Additional context**
You might have to delete the unused value in organization collection if it's duplicated / the organization shouldn't be active in that country (refer to organizations collection)
In case you have doubt which action shall you taken, you can always consult me first

**Comment by dodiws** [comment]
Created nodejs script to update organization collection with data imported from csv file. Functionally similar to `mongoimport --upsert` which can't do partial update in version 3.0. Still in test.

More info in [this comment](https://github.com/iMMAP/ngm-reportDesk/issues/45#issuecomment-1047505769).

**Comment by fakhrihawari** [comment]
already tested on DEV Server

**Comment by fakhrihawari** [comment]
already  on PROD
