### ISSUE TITLE
RH IQ Clean Older Reporting Structure

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#46]
**Describe the bug**
In Iraq there is a leftover of older reporting structure of one organization account per cluster, existing before 2019
in 2019 it has become one organization per country, and organizations updated only in Afghanistan
The same issue as https://github.com/iMMAP/ngm-reportDesk/issues/22 

**Context**
We realized this bug last year when a colleague from Ethiopia reported an issue of can not choose a warehouse created by the other colleague even though they're from the same organization. After further investigation, we know that this bug not only happening in Ethiopia but also in other countries as well. The only country that has already been cleaned up is Afghanistan only.

**To Reproduce**
1. Login using Iraq account
2. Go to '...'

**Expected behavior**
Clean all of related collections in ReportHub Iraq
1 organization should only have 1 organization_id in a country

**Screenshots**

**Additional context**
Kindly share the script here.

**Comment by dodiws** [comment]
Needs to run `find_refs_to_duplicate_orgs.js` script with `admin0pcode = 'IQ'` to remove duplicate organization and update organization references in collections.

More info in [this comment](https://github.com/iMMAP/ngm-reportDesk/issues/45#issuecomment-1047505769).

**Comment by fakhrihawari** [comment]
already  on PROD
