### ISSUE TITLE
RH SO Clean Older Reporting Structure

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#48]
**Describe the bug**
In Somalia there is a leftover of older reporting structure of one organization account per cluster, existing before 2019
in 2019 it has become one organization per country, and organizations updated only in Afghanistan
The same issue as https://github.com/iMMAP/ngm-reportDesk/issues/22 

**Context**
We realized this bug last year when a colleague from Ethiopia reported an issue of can not choose a warehouse created by the other colleague even though they're from the same organization. After further investigation, we know that this bug not only happening in Ethiopia but also in other countries as well. The only country that has already been cleaned up is Afghanistan only.

**To Reproduce**
1. Login using Somalia account
2. Go to
https://reporthub.org/desk/#/cluster/stocks/organization/5c593e3e6ee4b3c112d3a8e0/2022
https://reporthub.org/desk/#/cluster/stocks/organization/5c51522713b8c4724f72af39/2022
3. See Warehouse Locations and Stock Reports
4. See error where each link shows differently while the 2 of them are from the same organization

**Expected behavior**
Clean all of related collections in ReportHub Somalia
1 organization should only have 1 organization_id in a country

**Screenshots**
<img width="1680" alt="Screen Shot 2022-02-14 at 15 50 11" src="https://user-images.githubusercontent.com/28089698/153830875-cff032b2-d423-4054-86a9-5eebd17db396.png">

<img width="1680" alt="Screen Shot 2022-02-14 at 15 50 39" src="https://user-images.githubusercontent.com/28089698/153830914-698c07fe-3aba-4ce0-b88f-033db7176b2c.png">

**Additional context**
Kindly share the script here.

**Comment by fakhrihawari** [comment]
already try in DEV Server

**Comment by fakhrihawari** [comment]
Updated on PROD by running this command
```
cd /home/ubuntu/nginx/www/ngm-reportEngine/tasks/db

mongo localhost:27017/ngmHealthCluster find_refs_to_duplicate_orgs.js --eval 'var admin0pcode="SO"' --shell


// 1. DELETE DUPLICATE ORGANIZATIONS
    
    // show duplicate organizations
    run_query_func(find_duplicate_orgs_query)

    // delete duplicate organizations
    delete_duplicate_organizations()

    // check delete result
    run_query_func(find_duplicate_orgs_query)

    // 2. UPDATE REFERENCES TO DUPLICATE ORGANIZATIONS

    // show references to duplicate organizations
    show_refs_to_duplicate_orgs()

    // update references to duplicate organizations
    update_refs_to_duplicate_orgs()

    // check update result
    show_refs_to_duplicate_orgs()

    // 3. UPDATE REFERENCES TO DUPLICATE AND NON DUPLICATE ORGANIZATIONS

    // show references to duplicate and non duplicate organizations
    show_refs_to_duplicate_orgs(include_non_duplicate=true)

    // update references to duplicate and non duplicate organizations
    update_refs_to_duplicate_orgs(include_non_duplicate=true)

    // check update result
    show_refs_to_duplicate_orgs(include_non_duplicate=true)
```
