### ISSUE TITLE
RH AF Add New Cluster CCCM in ReportHub

### ISSUE THREAD

**Issue by fakhrihawari** [iMMAP/ngm-reportDesk#49]
**Is your feature request related to a problem? Please describe.**
Request from cluster 

**Describe the solution you'd like**
Update the following list accordingly based on their inputs from the returned configuration files

- [x] Activity List
- [x] Beneficiary List 
- [x] Donor List 
- [x] HRP Beneficiary List 

**Describe alternatives you've considered**

**Additional context**

**Comment by fakhrihawari** [comment]
Updated on DEV Server

<img width="1680" alt="Screen Shot 2022-02-25 at 14 20 42" src="https://user-images.githubusercontent.com/12655589/155672207-5019e83a-a3c7-4895-9b3c-c3fd74196285.png">

**Comment by fakhrihawari** [comment]
updated on PROD , Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/119

**Comment by rafinkanisa** [comment]
Done checking. Waiting for the clusters for their feedbacks
