### ISSUE TITLE
Email Notification of Request Delete Project still sending to deactivate user

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#5]
**Describe the bug**
I just checked & realized that the email notification for requesting to delete a project is still being sent to the deactivated user. The system should only send the notification to the active users.

**Context**
This is something that I've just found when I receive a delete request.

**To Reproduce**
1. Login using a common account
2. Click on any of the projects
2. Click on "request delete project"
3. Check the email is sending to 
4. Click my team to know the active account and deactivated account
5. You will see several email is sending to several deactivate account

**Expected behavior**
Send the email notification to only the active users who have the org admin rights

**Screenshots**
No screenshots

**Additional context**
No

**Comment by fakhrihawari** [comment]
And right now, the email will only send to users with active status
Link PR:
https://github.com/iMMAP/ngm-reportEngine/pull/47

Updated on PROD
