### ISSUE TITLE
RH SO Update Activity

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#51]
**Is your feature request related to a problem? Please describe.**
The Somalia Focal point is reaching out and asks to update the configuration list for "# of births assisted by a skilled birth attendant" to only enable girls and women

**Describe the solution you'd like**
Update the configuration as per request

**Describe alternatives you've considered**
No alternatives

**Additional context**

**Comment by fakhrihawari** [comment]
Already updated on DEV and PROD
