### ISSUE TITLE
RH AF Update Protection Activity

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#52]
**Is your feature request related to a problem? Please describe.**
The protection cluster is reaching out and request to add more activity in 2022 for the sub-sector of Child Protection.

**Describe the solution you'd like**
Add the activity as requested

**Describe alternatives you've considered**
No alternatives

**Additional context**
<img width="1287" alt="Screen Shot 2022-03-04 at 16 28 28" src="https://user-images.githubusercontent.com/28089698/156737000-604e6b58-3459-49b4-8bf8-6cbf2e9263e0.png">

**Comment by fakhrihawari** [comment]
already Updated on DEV and PROD
