### ISSUE TITLE
RH NG enable HH inputs

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#53]
**Is your feature request related to a problem? Please describe.**
The cluster focal point in Nigeria is requesting to enable the Households input in Sanitation - Waste Management - Cleaning Campaigns

**Describe the solution you'd like**
Enable the Households field

**Describe alternatives you've considered**
No alternative

**Additional context**
![image](https://user-images.githubusercontent.com/28089698/156957987-e23116e6-2d86-440a-a7af-c640e0a577d1.png)

**Comment by fakhrihawari** [comment]
Updated on DEV 
it will look like this
<img width="1143" alt="Screen Shot 2022-03-07 at 10 15 45" src="https://user-images.githubusercontent.com/12655589/156961817-436f9b50-603b-4755-bcbc-7d2c887a1d03.png">

**Comment by rafinkanisa** [comment]
OK. The HHs is automatically calculated based on location and we only enable the fields so they could put their own number

**Comment by fakhrihawari** [comment]
Updated on PROD
Link PR
https://github.com/iMMAP/ngm-reportHub/pull/122
