### ISSUE TITLE
RH NG Enable Individual input fields

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#54]
**Is your feature request related to a problem? Please describe.**
The cluster focal point reach me back and request another thing related with https://github.com/iMMAP/ngm-reportDesk/issues/53
They're requesting to also enable the individual field because there are many informal camps that doesn't have the individual number.

**Describe the solution you'd like**
Enable the individual input fields to be edited

**Describe alternatives you've considered**
No alternatives

**Additional context**
Same as previous
![image](https://user-images.githubusercontent.com/28089698/156989843-2044efe5-48ed-4ad0-b895-e35ccab4a888.png)

**Comment by fakhrihawari** [comment]
updated on DEV and PROD 
Link PR
https://github.com/iMMAP/ngm-reportHub/pull/123
