### ISSUE TITLE
RH NG Enable individuals & HH input

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#55]
**Is your feature request related to a problem? Please describe.**
The nigeria cluster focal point is reaching me to describe the problem in ReportHub. He then asked to enable all the input fields of Individual and Households but keep the calculation so that the partners which submitting report in location that doesn't have pre populated population could edit the number themselves.

**Describe the solution you'd like**
Enable the input fields of SADD group and Households input in WASH Nigeria that is active but disabled

**Describe alternatives you've considered**

**Additional context**

**Comment by fakhrihawari** [comment]
Updated on DEV and PROD
Link PR:  https://github.com/iMMAP/ngm-reportHub/pull/125
