### ISSUE TITLE
RH AF FSAC Add new activity list

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#56]
**Is your feature request related to a problem? Please describe.**
The FSAC cluster is coming back to me to request adding several activities such as :

- Food Assistance - in Kind - IPC4 (75% ration)
- Food Assistance - CBT - IPC4 (75% ration)
- Food Assistance - in Kind - IPC3 (50% ration)
- Food Assistance - CBT - IPC3 (50% ration)
- Unconditional Cash Transfer

**Describe the solution you'd like**
Add the activity as requested. This activity should be available starting from Jan 2022

**Describe alternatives you've considered**
No alternatives

**Additional context**
no screenshot

**Comment by fakhrihawari** [comment]
updated on DEV and PROD
