### ISSUE TITLE
RH AF CCCM Add New Beneficiary

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#57]
**Is your feature request related to a problem? Please describe.**
After meeting with the cluster coordinator in CCCM, I've got his clarification and he would like to add the following beneficiary :
Natural Disaster IDPs (displaced in 2022)

**Describe the solution you'd like**
Add the beneficiary type

**Describe alternatives you've considered**
No alternatives

**Additional context**

**Comment by fakhrihawari** [comment]
Updated on DEV and PROD
