### ISSUE TITLE
RH SO Add New Beneficiary List

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#59]
**Is your feature request related to a problem? Please describe.**
The Somalia focal point is reaching me and ask to add the following beneficiary :
Drought Non-IDPs 

**Describe the solution you'd like**
Add Drought Non-IDPs to the beneficiary list in ReportHub Somalia

**Describe alternatives you've considered**

**Additional context**

**Comment by fakhrihawari** [comment]
Updated on  DEV and PROD
