### ISSUE TITLE
RH AF Add Notes on the Monthly Report Page

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#6]
**Is your feature request related to a problem? Please describe.**
I'm communicating with the OCHA and they are requesting to have a note that explains what should partner choose about several population group to avoid confusion among the partners who are submitting the reports to the platform

**Describe the solution you'd like**
Add the notes with below sentences in Monthly Progress and Activity Plan:
HRP Beneficiary : Please include response to **Drought-Affected Non-displaced People** and **IDP returnees** under **Vulnerable People with Humanitarian Needs**. People displaced due to drought in 2022 should go under **New IDPs in 2022**.

I'm not sure if we have a configuration to show the notes according to the report month and year. If we have it, kindly show this starting from Jan 2022 - Dec 2022.

**Acceptance criteria**

- [x] Show this information in the Monthly/Biweekly Progress page
- [x] Show this information in the Activity Plan page (if the start/end project date is between Jan-Dec 2022)
- [x] Show this information to all clusters in Afghanistan
- [x] Show this information from Jan 2022 - Dec 2022 (optional)

**Describe alternatives you've considered**
No alternatives

**Additional context**
Please refer to below screenshots about the feature request here.
<img width="1118" alt="Screen Shot 2022-01-13 at 18 54 11" src="https://user-images.githubusercontent.com/28089698/149329886-d0eeb766-2e1a-40f3-a96f-4fa0ff369c28.png">

Please follow the sentences in the description. Not the one in the screenshots

**Comment by fakhrihawari** [comment]
![Screen Shot 2022-01-14 at 14 49 16](https://user-images.githubusercontent.com/12655589/149470706-aa6461b9-a731-465c-942a-995191742e42.png)

**Comment by fakhrihawari** [comment]
![Screen Shot 2022-01-17 at 08 37 14](https://user-images.githubusercontent.com/12655589/149687777-23786931-c0d0-43c8-b240-c66048f6d9a2.png)

Updated and only show in AF

**Comment by fakhrihawari** [comment]
Updated on DEV

**Comment by rafinkanisa** [comment]
Hi! Well done! I've just checked and it's good to hear that we have options to show the notification based on the time.
Just putting notes here if the start date of a Project Plan is in 2021 and it ends in 2022, the platform will show the users the notes also in the Activity Plan.

You can go to the PROD

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/106
