### ISSUE TITLE
RH FSAC Update Submitted Report Data

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#60]
**Is your feature request related to a problem? Please describe.**
As I've just received the completed data of activity in FSAC and there are many missing information has just been added. Therefore, this missing information should be made available in 2022 activity list and in the report that has already been submitted. The missing information include :

- grant type
- indicator
- update option of transfer type

Most of the information are metadata so, it is ok for us to update it directly from the database. It doesn't need any clarification from users.

**Describe the solution you'd like**

- [x] Identify all of the "Cash for Work" activity that has been submitted starting at Jan 2022 to Feb 2022 (current date)
- [x] Update the indicator of Cash for Work (currently, it's blank)
- [x] Update the activity configuration of Cash for Work with the defined indicator to be started from Jan 2022 (currently it's from Mar 2022)
- [x] Identify all of the cash-based activity that has been submitted in Jan - Feb 2022 (current date)
- [x] Update the grant type of each of those cash-based activities accordingly (currently, it's blank)
- [x] Identify all of the cash-based activity that has default calculation by HHs which has been submitted in Jan - Feb 2022 (current date)
- [x] Update the transfer type option by following : if the default is Households, then update the db to Households
- [x] Update the activity configuration with options transfer type being enable to be started from Jan 2022 (currently it's from Mar 2022)
- [x] Identify all of the cash-based activity that has default calculation by 1 time transfers which has been submitted in Jan - Feb 2022 (current date)
- [x] Update the transfers option by following : if the default is 1, then update the db to 1
- [x] List all of the 0 times transfers and give me the list so I could provide guidance on how to proceed
- [x] Update the activity configuration with options transfers being enable to be started from Jan 2022 (currently it's from Mar 2022)

**Describe alternatives you've considered**

**Additional context**

**Comment by fakhrihawari** [comment]
There are 19 activities that have already been submitted by users under fsac in 2022
only for activity need to updated
Script to updated:
Check this activity
- db.beneficiaries.find({ admin0pcode: "AF", report_year: 2022, cluster_id: "fsac", activity_type_id: "livelihood_support", activity_type_name: "Livelihood Support", activity_description_id: "livelihood_support_cash_for_work", activity_description_name: "Cash for Work", indicator_name: { $eq: "" } , _id: { $ne: ObjectId('621f68ee33a9ebb323bfed71') }}).count()
- db.beneficiaries.find({ admin0pcode:"AF",report_year: 2022, cluster_id: "fsac", activity_type_id: "livelihood_support", activity_type_name: "Livelihood Support", activity_description_id: "livelihood_support_cbt", activity_description_name: "Livelihood Support - CBT", indicator_name: "# of shock affected and vulnerable (natural disaster affecteds, people affected by COVID-19, and food insecure IPC phase 3 and 4 people) women, men and children of all ages who receive adequate livelihoods assistance in a timely manner." }).count()
- db.beneficiaries.find({ admin0pcode:"AF",report_year: 2022, cluster_id: "fsac", activity_type_id: "food_assistance", activity_type_name: "Food Assistance", activity_description_id: "food_assistance_cbt", activity_description_name: "Food Assistance - CBT", indicator_name: "# of conflict affected IDP women, men and children of all ages who receive adequate cash assistance, in a timely manner." }).count()
- db.beneficiaries.find({ admin0pcode: "AF", report_year: 2022, cluster_id: "fsac", activity_type_id: "agriculture_livelihood_support", activity_type_name: "Agriculture Based Livelihood Support", activity_description_id: "seed_distribution_other_cbt", activity_description_name: "Other Seed Distribution - CBT", indicator_name: "# of shock affected and vulnerable (natural disaster affecteds, people affected by COVID-19, and food insecure IPC phase 3 and 4 people) women, men and children of all ages who receive adequate livelihoods assistance in a timely manner." }).count()
- db.beneficiaries.find({ admin0pcode: "AF", activity_description_id: "livelihood_support_cbt", activity_description_name: "Livelihood Support - in Kind", indicator_name: "# of shock affected and vulnerable (natural disaster affecteds, people affected by COVID-19, and food insecure IPC phase 3 and 4 people) women, men and children of all ages who receive adequate livelihoods assistance in a timely manner." }).count()
- db.beneficiaries.find({ admin0pcode: "AF", activity_description_id: "livelihood_support_cbt", indicator_name: "# COVID-19 affected people who receive disinfecting, hygiene and awareness support for COVID-19 minimization" }).count()

And then updated:
- db.beneficiaries.update({ admin0pcode: "AF", report_year: 2022, cluster_id: "fsac", activity_type_id: "livelihood_support", activity_type_name: "Livelihood Support", activity_description_id: "livelihood_support_cash_for_work", activity_description_name: "Cash for Work", indicator_name: { $eq: "" }, _id: { $ne: ObjectId('621f68ee33a9ebb323bfed71') }}, { $set: { "transfer_category_id": "household", "transfer_category_name": "Household", "grant_type_id": "conditional_unrestricted", "grant_type_name": "Conditional, Unrestricted", transfer_type_id: 1, transfer_type_value: 1, indicator_id: "no_of_shock_affected_and_vulnerable_natural_disaster_affecteds_people_affected_by_covid_19_and_food_insecure_ipc_phase_3_and_4_people_women_men_and_children_of_all_ages_who_receive_adequate_livelihoods_assistance_in_a_timely_manner.", indicator_name: "# of shock affected and vulnerable (natural disaster affecteds, people affected by COVID-19, and food insecure IPC phase 3 and 4 people) women, men and children of all ages who receive adequate livelihoods assistance in a timely manner."}},{multi:true})
- db.beneficiaries.update({ admin0pcode: "AF", report_year: 2022, cluster_id: "fsac", activity_type_id: "livelihood_support", activity_type_name: "Livelihood Support", activity_description_id: "livelihood_support_cbt", activity_description_name: "Livelihood Support - CBT", indicator_name: "# of shock affected and vulnerable (natural disaster affecteds, people affected by COVID-19, and food insecure IPC phase 3 and 4 people) women, men and children of all ages who receive adequate livelihoods assistance in a timely manner." }, { $set: { "transfer_category_id": "household", "transfer_category_name": "Household", "grant_type_id": "unconditional_unrestricted", "grant_type_name": "Unconditional, Unrestricted", transfer_type_id: 1, transfer_type_value: 1}},{multi:true})
- db.beneficiaries.update({ admin0pcode: "AF", report_year: 2022, cluster_id: "fsac", activity_type_id: "food_assistance", activity_type_name: "Food Assistance", activity_description_id: "food_assistance_cbt", activity_description_name: "Food Assistance - CBT", indicator_name: "# of conflict affected IDP women, men and children of all ages who receive adequate cash assistance, in a timely manner." }, { $set: { "transfer_category_id": "household", "transfer_category_name": "Household", "grant_type_id": "unconditional_unrestricted", "grant_type_name": "Unconditional, Unrestricted"}},{multi:true})
- db.beneficiaries.update({ admin0pcode: "AF", report_year: 2022, cluster_id: "fsac", activity_type_id: "agriculture_livelihood_support", activity_type_name: "Agriculture Based Livelihood Support", activity_description_id: "seed_distribution_other_cbt", activity_description_name: "Other Seed Distribution - CBT", indicator_name: "# of shock affected and vulnerable (natural disaster affecteds, people affected by COVID-19, and food insecure IPC phase 3 and 4 people) women, men and children of all ages who receive adequate livelihoods assistance in a timely manner." }, { $set: { "grant_type_id": "unconditional_unrestricted", "grant_type_name": "Unconditional, Unrestricted", "transfer_category_id": "household", "transfer_category_name": "Household", transfer_type_id: 1, transfer_type_value: 1 }},{multi:true})
- db.beneficiaries.update({ admin0pcode: "AF", activity_description_id: "livelihood_support_cbt", activity_description_name: "Livelihood Support - in Kind", indicator_name: "# of shock affected and vulnerable (natural disaster affecteds, people affected by COVID-19, and food insecure IPC phase 3 and 4 people) women, men and children of all ages who receive adequate livelihoods assistance in a timely manner." }, { $set: { activity_description_id: "livelihood_support_in_kind" }},{multi:"true"})
-db.beneficiaries.update({ admin0pcode: "AF", activity_description_id: "livelihood_support_cbt", indicator_name: "# COVID-19 affected people who receive disinfecting, hygiene and awareness support for COVID-19 minimization" }, { $set: { activity_description_id: "livelihood_support", activity_description_name:"Livelihood Support"}},{multi:true})

**Comment by fakhrihawari** [comment]
Updated on DEV

**Comment by fakhrihawari** [comment]
Updated on PROD
