### ISSUE TITLE
RH NG WASH Beneficiaries is showing late

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#61]
**Describe the bug**
The beneficiary number is showing late. Takes around 2 minutes

**Context**
Is this bug request coming from a partner ? in this case please note in which context it was requested? and who was the contact point? 
This is a request from Nigeria WASH cluster focal point who found this bug and reported in a call meeting with Rafinka.

**To Reproduce**
1. Login using Nigeria account
2. Go to https://www.reporthub.org/desk/#/cluster/projects/report/62028e0b28a857fa54a02cd3/621d7e2233a9ebb323bf2d1c
3. Try to add report in 'Borno, Damboa, Damboa Central, CENTRAL PRIMARY SCHOOL DAMBOA' with parameter the same as in the screenshots
4. See error where the beneficiaries number is 0 and after some time it changes

**Expected behavior**
The calculated beneficiary number shouldn't be showing late. Once the parameters match, the calculation should show immediately

**Screenshots**
screenshots for steps point 3
![image](https://user-images.githubusercontent.com/28089698/159410335-fa5cb241-0ab8-4d9b-ba8b-bb9296e15090.png)

screenshots for steps point 4
![image](https://user-images.githubusercontent.com/28089698/159410311-d92863ed-b78a-442c-97dd-f92073206631.png)

**Additional context**

**Comment by fakhrihawari** [comment]
already found where is the problem and already fixed it.
Link PR: https://github.com/iMMAP/ngm-reportHub/pull/127
