### ISSUE TITLE
RH AF Protection Update Indicator

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#62]
**Is your feature request related to a problem? Please describe.**
The protection cluster IM reaching out and request to update the following indicator 
#. of girls and boys at risk, including unaccompanied and separated children, and child survivors of GBV identified, documented, and received case management services

into 
#. of girls and boys at risk, including unaccompanied and separated children, and child survivors of different protection risks identified, documented, and received case management services.

**Describe the solution you'd like**
Update the indicator as requested. There will be 5 activity detail under CPiE affected by this update.

**Acceptance Criteria**

- [x] Indicator name updated for the submitted report from Jan 2022 to current
- [x] Indicator id updated for the submitted report from Jan 2022 to current

**Describe alternatives you've considered**
No alternatives

**Additional context**

**Comment by fakhrihawari** [comment]
Testing script on Local
```
db.beneficiaries.find({
    admin0pcode: "AF",
    cluster_id: "protection",
    activity_type_id: "cpie",
    activity_description_id: "integrated_case_management_services",
    report_year: 2022,
    indicator_id: "no_of_girls_and_boys_at_risk_including_unaccompanied_and_separated_children_and_child_survivors_of_gbv_identified_documented_and_received_case_management_services",
    indicator_name: "# of girls and boys at risk, including unaccompanied and separated children, and child survivors of GBV identified, documented, and received case management services"
}).count()
```
```
db.beneficiaries.update({
    admin0pcode: "AF",
    cluster_id: "protection",
    activity_type_id: "cpie",
    activity_description_id: "integrated_case_management_services",
    report_year: 2022,
    indicator_id:"no_of_girls_and_boys_at_risk_including_unaccompanied_and_separated_children_and_child_survivors_of_gbv_identified_documented_and_received_case_management_services",
    indicator_name: "# of girls and boys at risk, including unaccompanied and separated children, and child survivors of GBV identified, documented, and received case management services"
}, { $set: {    indicator_id:"no_of_girls_and_boys_at_risk_including_unaccompanied_and_separated_children_and_child_survivors_of_different_protection_risks_identified_documented_and_received_case_management_services.",
    indicator_name: "# of girls and boys at risk, including unaccompanied and separated children, and child survivors of different protection risks identified, documented, and received case management services."
            }
    },{multi:true}
)
```

**Comment by rafinkanisa** [comment]
You can try on DEV using the most recent DB backup

**Comment by fakhrihawari** [comment]
Updated on DEV

**Comment by rafinkanisa** [comment]
Done check. Can go to PROD
Don't forget to update also the csv for activities

**Comment by fakhrihawari** [comment]
Updated on PROD
