### ISSUE TITLE
Moving HRP Beneficiary Type to API

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#64]
**Is your feature request related to a problem? Please describe.**
Currently, to update the HRP Beneficiary list is by updating the code directly. As this list will always be changing in the future, it would be hard to maintain if we have to update the code every time the list is updated. We have been thinking to move this since last year but until now it's still postponed. Reference https://github.com/rafinkanisa/ngm-reportDesk/issues/26

**Describe the solution you'd like**
Make the HRP Beneficiary list can be updated via database

**Acceptance Criteria**

- [x] List can be updated easily through script

**Describe alternatives you've considered**
Keep the HRP Beneficiary list updated through hard code

**Additional context**

**Comment by fakhrihawari** [comment]
Updated on DEV

**Comment by fakhrihawari** [comment]
updated on PROD
link PR:
https://github.com/iMMAP/ngm-reportHub/pull/130
https://github.com/iMMAP/ngm-reportEngine/pull/56


script to move data to the server

```
mongoimport -d ngmHealthCluster -c hrpbeneficiarytypes --drop --headerline --type csv --file /home/ubuntu/data/csv/hrpbeneficiarytypes.csv
mongo < /home/ubuntu/nginx/www/ngm-reportEngine/tasks/db/lists/process_hrp_beneficiarytypes.js
```
