### ISSUE TITLE
RH AF Stock Report is incorrect

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#66]
**Describe the bug**
The submitted stock report is saying EiEWG while the actual report is ESNFI. Tarpaulin should come under ESNFI

**Context**
Is this bug request coming from a partner ? in this case please note in which context it was requested? and who was the contact point? 
I found this bug when I check the data after producing some statistics needed to show the engagement rate of ReportHub

**To Reproduce**
1. Login into Afghanistan account
2. Go to https://reporthub.org/desk/#/cluster/stocks/report/58e1f9d816a5ecf8707106f0/60177cc14e21794d62e3e93c
3. Scroll down to 'Balkh, Mazar-e-Sharif, UNICEF Mazar WHS' 
4. See error where the selected cluster in the dropdown is "EiEWG" while the details is "ESNFI", the "Stock Type" is also missing while this shouldn't happen

**Expected behavior**
Showing the correct cluster
Showing the Stock Type

**Screenshots**
<img width="1156" alt="Screen Shot 2022-03-28 at 10 30 21" src="https://user-images.githubusercontent.com/28089698/160520800-56d81d4e-4dad-4308-8d85-cc4df8d9dc24.png">

**Additional context**

**Comment by fakhrihawari** [comment]
Updated on DEV and PROD
Script to check which record need to update:
```
var clusters= [{cluster:"EiEWG",cluster_id:"eiewg"},
{cluster:"ESNFI",cluster_id:"esnfi"},
{cluster:"FSAC",cluster_id:"fsac"},
{cluster:"Health",cluster_id:"health"},
{cluster:"Protection",cluster_id:"protection"},
{cluster:"WASH",cluster_id:"wash"}]

clusters.forEach(function(c){
    var sin = ('^' + c.cluster)
    print(sin)
    var count = db.stock.find({stock_item_name:{$regex:sin},cluster_id:{$ne:c.cluster_id}}).count();
    print("CLUSTER: " + c.cluster +" COUNT: "+ count);
})
```
Script to update the record:

```
var clusters = [{ cluster: "EiEWG", cluster_id: "eiewg" },
{ cluster: "ESNFI", cluster_id: "esnfi" },
{ cluster: "FSAC", cluster_id: "fsac" },
{ cluster: "Health", cluster_id: "health" },
{ cluster: "Protection", cluster_id: "protection" },
{ cluster: "WASH", cluster_id: "wash" }]

clusters.forEach(function (c) {
    var sin = ('^' + c.cluster)
    db.stock.update({ stock_item_name: { $regex: sin }, cluster_id: { $ne: c.cluster_id } },{$set:{cluster:c.cluster,cluster_id:c.cluster_id}},{multi:true});
})
```

**Comment by rafinkanisa** [comment]
Done check. Looks good
