### ISSUE TITLE
RH AF Filter Location in 5W Dashboard

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#67]
**Is your feature request related to a problem? Please describe.**
Last year we still have some projects that actively submitting reports using the old location attribute. Starting from 2022, we have ensured that none of those project is still active. This has been a request coming from various stakeholders since last year. This filter is creating a confusion among the partners and the IM.

**Describe the solution you'd like**
In the 5W Dashboard page, if the user is selecting period starting from Jan 2022 onwards, the province filter should only show the new location only (remove all old locations).

**Describe alternatives you've considered**

**Additional context**
<img width="282" alt="Screen Shot 2022-03-28 at 16 37 46" src="https://user-images.githubusercontent.com/28089698/160522997-40f75ebb-7462-41b1-96bd-68b247fc7f42.png">

**Comment by fakhrihawari** [comment]
updated on DEV

<img width="339" alt="Screen Shot 2022-03-29 at 13 51 53" src="https://user-images.githubusercontent.com/12655589/160551092-c83b8419-4829-43a2-9635-ca5b0460430f.png">

**Comment by fakhrihawari** [comment]
updated on PROD
Link PR
https://github.com/iMMAP/ngm-reportHub/pull/131

**Comment by rafinkanisa** [comment]
Looks good to me. Great! Thanks
