### ISSUE TITLE
Project Code downloaded as 0

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#68]
**Describe the bug**
I tried to create a project plan with '000' as the project code. When I tried to download the report, the project code in the downloaded file becomes '0'

**Context**
Is this bug request coming from a partner ? in this case please note in which context it was requested? and who was the contact point? 
This is something I just spotted upon checking

**To Reproduce**
1. Create a new project plan
2. Type '000' in the project code
3. Save the project plan
4. Submit a report
5. Download the submitted report

**Expected behavior**
The project code in the downloaded file should return the same as what the user is typing.

**Screenshots**

**Additional context**

Project code in the project plan
<img width="192" alt="Screen Shot 2022-03-30 at 10 20 57" src="https://user-images.githubusercontent.com/28089698/161468646-01feb8af-9a8d-48d2-9812-ff494c78301c.png">

Project code in the downloaded file
<img width="99" alt="Screen Shot 2022-03-30 at 10 10 37" src="https://user-images.githubusercontent.com/28089698/161468662-a2a04d41-f577-4a35-8578-c6f9753ab9d7.png">

**Comment by fakhrihawari** [comment]
For now, the solution that I found is to put " (quote mark) before and after string for this case 
it will look like this in csv file:
<img width="119" alt="Screen Shot 2022-04-04 at 10 37 53" src="https://user-images.githubusercontent.com/12655589/161479337-1ecd448f-ffaa-4cf4-96ab-7053b53f8b24.png">

**Comment by fakhrihawari** [comment]
after checking and trying opening CSV files on other software (google Sheets) besides excel and numbers in mac. it turns out that the value of the project code is not altered in the CSV file or the same as in DB
