### ISSUE TITLE
Page when project is missing

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#70]
**Is your feature request related to a problem? Please describe.**
We have created a delete request feature where the notification send to the admins. Most often, there are multiple admin in one organization. If one of the admin has deleted the project, when the other admin is clicking the link of the requested project to be deleted, the page is only showing blank page which confuses the user whether the loading is complete or not.

**Describe the solution you'd like**
Instead of blank page, make a 404 page

**Acceptance criteria**

- [x] Clicking on a deleted project will redirect to the 404 page

**Describe alternatives you've considered**

**Additional context**

**Comment by fakhrihawari** [comment]
updated on DEV and PROD

<img width="1387" alt="Screen Shot 2022-04-05 at 13 09 58" src="https://user-images.githubusercontent.com/12655589/161690038-00381efb-920b-4e3f-9529-157d029ea1a3.png">

Link PR : 
https://github.com/iMMAP/ngm-reportHub/pull/134
