### ISSUE TITLE
Project Set to Complete but Monthly Progress is still generating New TODO Reports

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#73]
**Describe the bug**
Monthly Progress still opening a new reports to be completed even though the project has been set to complete.
It is found difficult to track which project should be reported if we leave this bug as is.

**Context**
Is this bug request coming from a partner ? in this case please note in which context it was requested? and who was the contact point? 
ex: This is a request from X who found this bug and reported in a call meeting with Y.
Just found this when checking the DRC report.

**To Reproduce**
1. Login using Afghanistan account
2. Go to 'https://reporthub.org/desk/#/cluster/projects/report/600ceca61a6763d231227a90'
3. See error where the project has been set to complete but there is still "Progress Update To Do" showing

**Expected behavior**
When the project has been set to complete, the monthly progress shouldn't be adding more reports to do in each month.
Move all of the open report in project that has been set to complete to Progress Update Complete

**Acceptance Criteria**

- [x] Stop the creation of to do report in each new month if project has been set to complete
- [x] Move all the todo report to complete (leave blank) if project has been set to complete

**Screenshots**

**Additional context**
Kindly test below use case:

1. A user has marked a project as complete in Oct 2021
2. This user then re-activate the project mentioned in point 1 in Jan 2022

What will happen?
Will the to do reports from Oct 2021 - Jan 2022 be automatically created after this user re-activate the project?

**Comment by fakhrihawari** [comment]
Already testing in local and will test to DEV Server

**Comment by fakhrihawari** [comment]
Do we need to change the status of the report to complete or just remove the report from the project?

**Comment by fakhrihawari** [comment]
Updated on DEV

**Comment by rafinkanisa** [comment]
I think would be better to change the status to complete

**Comment by fakhrihawari** [comment]
updated on PROD 
Link PR
https://github.com/iMMAP/ngm-reportEngine/pull/60

Script to update:
```
db.report.find({ report_status: "todo", project_status: "complete", report_submitted: { $exists: false } }).count()
db.report.find({ report_status: "todo", project_status: "complete", report_submitted: { $exists: true } }).count()

db.report.update({ report_status: "todo", project_status: "complete", report_submitted: { $exists: false } },{$set:{report_status:"complete"}},{multi:true});
db.report.update({ report_status: "todo", project_status: "complete", report_submitted: { $exists: true } }, { $set: { report_status: "complete" } }, { multi: true });

db.beneficiaries.find({ report_status: "todo", project_status: "complete", report_submitted: { $exists: true } }).count()

db.beneficiaries.update({ report_status: "todo", project_status: "complete" }, { $set: { report_status: "complete" } }, { multi: true });
```
