### ISSUE TITLE
RH AF CCCM Site Type

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#75]
**Is your feature request related to a problem? Please describe.**
I've just received some clarifications from the CCCM Coordinator. As we discussed before that CCCM WG would like to use ReportHub, we'll have to set some things such as the Site Type option.

**Describe the solution you'd like**
Add below list in the Site Type options:

- Informal Settlement (ISET) & Spontaneous IDP Site    
- Urban
- Rural
- Other

Acceptance Criteria

- [x] Only the above list shown when choosing only CCCM
- [x] If it's multicluster project, it should append other Site Type (behaviour is the same as Protection)

**Describe alternatives you've considered**

**Additional context**

**Comment by fakhrihawari** [comment]
updated on DEV

<img width="434" alt="Screen Shot 2022-04-13 at 11 13 24" src="https://user-images.githubusercontent.com/12655589/163098835-e60266d7-6f07-4c2c-b931-1c9642316e5f.png">

**Comment by rafinkanisa** [comment]
I just check but it's showing a list which is not under CCCM while I only choose CCCM. It should show only the list I mention above and if it's a multicluster, other list will be appended I suppose (like in Protection)

**Comment by fakhrihawari** [comment]
already fix it on DEV

**Comment by rafinkanisa** [comment]
Done check can go to PROD

**Comment by fakhrihawari** [comment]
updated on PROD
link PR:
https://github.com/iMMAP/ngm-reportHub/pull/135
