### ISSUE TITLE
RH AF CCCM Activity List Update

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#77]
**Is your feature request related to a problem? Please describe.**
I've just received some updates from the CCCM Coordinator. As we discussed before that CCCM WG would like to use ReportHub, we'll have to update the activity list according to their request.

**Describe the solution you'd like**
Update the activity list according to the answer from CCCM Coordinator

**Describe alternatives you've considered**

**Additional context**

**Comment by rafinkanisa** [comment]
Done updating the CSV files. Kindly proceed to DEV thanks!

**Comment by fakhrihawari** [comment]
Updated on DEV

**Comment by rafinkanisa** [comment]
Hi! I just checked
I think this one is still using the old version. The units should be # of Training Sessions

<img width="1111" alt="Screen Shot 2022-04-13 at 15 14 11" src="https://user-images.githubusercontent.com/28089698/163131798-6af80749-a554-4d73-ab20-d0cead157d7e.png">

**Comment by fakhrihawari** [comment]
already fix it on DEV

**Comment by rafinkanisa** [comment]
good. can go to PROD

**Comment by fakhrihawari** [comment]
Updated on PROD
