### ISSUE TITLE
Opening link before logged in not redirect to the link after login

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#8]
Moving https://github.com/rafinkanisa/ngm-reportDesk/issues/105

**Is your feature request related to a problem? Please describe.**
Whenever I or partners open a reporthub link before logging to the platform, I'm not redirected to the destinated link after successfully logging in. Instead, the first screen that always pop up after login is the "My Admin" page.

How to do :

1. Open an incognito window
2. Paste the link https://reporthub.org/desk/#/cluster/projects/report/612f231d7fd758f3603104ef/612f231d7fd758f3603104f7
3. Login using your credentials
4. See that it is not redirected to the destinated link

**Describe the solution you'd like**
Redirect to the link that should be opened after successfully login.
It would be like implementing a "?next=zzz" in the link.

**Describe alternatives you've considered**

**Additional context**

**Comment by fakhrihawari** [comment]
Updated on DEV

**Comment by fakhrihawari** [comment]
Demo

https://user-images.githubusercontent.com/12655589/159428447-f60377f6-4a58-4fa6-8571-0aeb424be0f3.mp4

**Comment by rafinkanisa** [comment]
Done checking. Can go to the PROD

**Comment by fakhrihawari** [comment]
Updated on PROD, Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/128
