### ISSUE TITLE
RH AF Copy Last Report Button not working

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#9]
**Describe the bug**
Couldn't copy the last report in biweekly progress report

**Context**
I just found out this bug when randomly trying the copy button

**To Reproduce**
1. Login using your Afghanistan account
2. Go to https://reporthub.org/desk/#/cluster/projects/group/61dd62179fb74f71688bd50e/61dd62179fb74f71688bd528
3. Click on 'Copy Last Report'
4. See error of no last report could be copied while there is a report submitted in the previous period

**Expected behavior**
Successfully copying the previous report period (in the example, successfully copying the December period 2)

**Screenshots**

**Additional context**
The reporting partners will be frustrated if this bug is not fixed because they will have to submit their report one by one. This is one of the tool have been heavily used by the partner

**Comment by fakhrihawari** [comment]
Already found  where the problem is, and will make a pull request to solve this bug

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/102
